config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
 
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :categories, only: %i[index new create show], to: 'show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    post '/vote/', to: 'votes#create'
    delete '/vote/', to: 'votes#destroy'
  end
  scope :sessions do
    get 'sign_out' => 'sessions#destroy'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: true }, length: { in: 3..20 }
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0 }

  has_many :articles, -> { order(created_at: :desc) }

  scope :priority_sorted, -> { order(priority: :asc) }
  scope :importants, -> { priority_sorted.limit(4) }
  scope :important_with_articles, -> { importants.includes(articles: [image_attachment: :blob]) }

  def latest_article
    articles.first
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.includes(:articles).order(priority: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.includes(:articles).find(params[:id])
    @articles = @category.articles.includes(:votes).includes(:author).order(created_at: 'DESC')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :priority %>
    <%= form.number_field :priority, class:"form-control", minlength:1%>
  </div>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", minlength:5 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice">
  <%= notice %>
</p>
<div class="container">
  <div class="row mt-5">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <h1 class="text-center pt-3">Categories</h1>
      <div class="card">
        <div class="card-body">
          <div class="cards-holder d-flex flex-column">
            <% @categories.each do |category| %>
              <div class="my-card ">
                <h3>
                  <%= category.name.capitalize %>
                  <td>
                    <%= link_to 'Show' , category %>
                  </td>
                </h3>
              </div>
            <% end %>
          </div>   
        </div>
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

<%= yield %>
<%= render "layouts/footer" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="h-100 mt-5 pt-2">

  <% reverse=true %>
    <% @articles.each_slice(2) do |article1, article2| %>
      <% if reverse %>
        <div class="row vertical-card">
          <div class="col-6 ha">
            <div class="row">
              <div class="col-6">
                <%= link_to article_path(article1.id) do %>
                  <%= image_tag "#{article1.image.downcase}" , class:"cover-img full" %>
                    <% end %>
              </div>
              <div class="col-6 p-3 d-flex flex-column justify-content-between bg-purple">
                <h3 class="my-card-catt">
                  <%= @category.name.capitalize %>
                </h3>
                <strong>
                  <h4>
                    <%=article1.title%>
                  </h4>
                </strong>
                <p class="my-card-textt">
                  <%=article1.text%>
                </p>
                <p class="text-wrap">BY:<strong>
                    <%=article1.author.name%>
                  </strong></p>
                  <%= link_to 'Back', categories_path %>
              </div>
            </div>
          </div>
          <% if !article2.nil? %>
            <div class="col-6 ha">
              <div class="row">
                <div class="col-6">
                  <%= link_to article_path(article2.id) do %>
                    <%= image_tag "#{article2.image.downcase}" , class:"cover-img full" %>
                      <% end %>
                </div>
                <div class="col-6 p-3 d-flex flex-column justify-content-between bg-purple">
                  <h3 class="my-card-catt">
                    <%= @category.name.capitalize %>
                  </h3>
                  <strong>
                    <h4>
                      <%=article2.title%>
                    </h4>
                  </strong>
                  <p class="my-card-textt">
                    <%=article2.text%>
                  </p>
                  <p class="text-wrap">BY:<strong>
                      <%=article2.author.name%>
                    </strong></p>
                    <%= link_to 'Back', categories_path %>
                </div>
              </div>
            </div>
            <% end %>
        </div>
        <% reverse=false %>
          <% else %>

            <div class="row vertical-card">
              <div class="col-6 ha">
                <div class="row">
                  <div class="col-6 p-3 d-flex flex-column justify-content-between bg-purple">
                    <h3 class="my-card-catt">
                      <%= @category.name.capitalize %>
                    </h3>
                    <strong>
                      <h4>
                        <%=article1.title%>
                      </h4>
                    </strong>
                    <h6 class="my-card-textt">
                      <%=article1.text%>
                    </h6>
                    <p class="text-wrap">BY:<strong>
                        <%=article1.author.name%>
                      </strong></p>
                      <%= link_to 'Back', categories_path %>
                  </div>
                  <div class="col-6">
                    <%= link_to article_path(article1.id) do %>
                      <%= image_tag "#{article1.image.downcase}" , class:"cover-img full" %>
                        <% end %>
                  </div>
                </div>
              </div>
              <% if !article2.nil? %>
                <div class="col-6 ha">
                  <div class="row">
                    <div class="col-6 p-3 d-flex flex-column justify-content-between bg-purple">
                      <h3 class="my-card-catt">
                        <%= @category.name.capitalize %>
                      </h3>
                      <strong>
                        <h4>
                          <%=article2.title%>
                        </h4>
                      </strong>
                      <p class="my-card-textt">
                        <%=article2.text%>
                      </p>
                      <p class="text-wrap">BY:<strong>
                          <%=article2.author.name%>
                        </strong></p>
                        <%= link_to 'Back', categories_path %>
                    </div>
                    <div class="col-6">
                      <%= link_to article_path(article2.id) do %>
                        <%= image_tag "#{article2.image.downcase}" , class:"cover-img full" %>
                          <% end %>
                    </div>
                  </div>
                </div>
                <% end %>
            </div>
            <% reverse=true %>
              <% end %>
                <% end %>
</div><br><br>

<%= yield %>
<%= render "layouts/footer" %>