config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
 
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :categories, only: %i[index new create show], to: 'show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
    post '/vote/', to: 'votes#create'
    delete '/vote/', to: 'votes#destroy'
  end
  scope :sessions do
    get 'sign_out' => 'sessions#destroy'
  end
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg  fixed-bottom bg-purple">
    <div class="container-fluid">
      <a class="navbar-brand padding-right white" href="/articles"><div>Movie Guru <span class="after"></span></div></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
              <li class="nav-item p-2">
                  <%= link_to 'Privacy Policy', "", class: "nav-link active orange" %>
              </li>
              <li class="nav-item p-2">
                  <%= link_to 'Terms & Conditions', "", class: "nav-link active orange" %>
              </li>
              <li class="nav-item p-2">
                  Copyright &copy; 2021. All rights reserved
              </li>
          </ul>
          <ul class="navbar-nav align-items-center">
              <li class="nav-item">
                  Contact with us: 
              </li> 
              <li class="nav-item">
                  <a class="nav-link orange"><i class="fab fa-facebook"></i></a> 
              </li> 
              <li class="nav-item" >
                  <a class="nav-link orange"><i class="fab fa-twitter"></i></i></a> 
              </li>
              <li class="nav-item" >
                  <a class="nav-link orange"><i class="fab fa-instagram"></i></a> 
              </li>
        </ul>
      </div>
    </div>
  </nav> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-purple ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Movie Guru</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <% if logged_in? %>
          <%= link_to "Home", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Article", new_article_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Categories", categories_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
          <h6 class="pt-2">
            <%= session[:username] %>
          </h6>
          <p class="control">
            <%= link_to "Sign Out", sign_out_url, class: "nav-link" %>
          </p>
          <% else %>
          <li class="control">
            <%= link_to "Sign In", new_session_path, class: "nav-link" %> 
          </li> |
          <li class="control">
            <%= link_to "Register", new_user_path, class: "nav-link active" %>
          </li>
          <% end %>
        
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Guru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>